# Use a Python base image
FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app


COPY pip_wheels/ /wheels/
COPY requirements.txt .


RUN pip install --no-cache-dir --find-links=/wheels --no-index -r requirements.txt

COPY yolo11n.pt .
COPY model_inference.py .

CMD ["python", "model_inference.py"]