FROM python:3.12
RUN apt-get update && \
    apt-get install -y  \
        libgl1 \
        libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

# Copy common utilities
COPY common/__init__.py /app/common/
COPY common/health.py /app/common/

COPY view-process/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY view-process/web_viewer.py .


EXPOSE 5000


CMD ["python", "web_viewer.py"]