# Use a Python base image
FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*
# Set the working directory inside the container
WORKDIR /app

# Copy common utilities
COPY common/__init__.py /app/common/
COPY common/health.py /app/common/

# Copy the requirements file and install dependencies
# COPY kafka-consumer/pip_wheels/ /wheels/
COPY kafka-consumer/requirements.txt .
RUN pip install --no-cache-dir --find-links=/wheels -r requirements.txt

# Copy the application code
COPY kafka-consumer/preprocessor.py .

# Command to run the application
CMD ["python", "preprocessor.py"]