FROM python:3.12-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libgl1 \
        libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

# Copy common utilities
COPY common/__init__.py /app/common/
COPY common/health.py /app/common/

COPY view-detection/requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt

COPY view-detection/detector_viewer.py .


EXPOSE 7000

CMD ["python", "detector_viewer.py"]